In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

In [2]:
import pandas as pd

train_ds = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/train.csv')
train_ds

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
test_ds = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/test.csv')
test_ds

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [4]:
train_ds['SalePrice'].mean()

180921.19589041095

In [5]:
test_ds['SalePrice'] = train_ds['SalePrice'].mean()
test_ds

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,180921.19589
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,180921.19589
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,180921.19589
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,180921.19589
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,180921.19589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,180921.19589
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,180921.19589
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,180921.19589
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,180921.19589
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,180921.19589

In [6]:
test_ds[['Id', 'SalePrice']].to_csv('house_predict_submission_01.csv', index=False)

In [7]:
from copy import deepcopy

train_ds_sub = deepcopy(train_ds[['MSSubClass', 'LotArea', 'SalePrice']])
train_ds_sub = train_ds_sub.fillna(train_ds_sub.mean())
train_ds_sub

      MSSubClass  LotArea  SalePrice
0             60     8450     208500
1             20     9600     181500
2             60    11250     223500
3             70     9550     140000
4             60    14260     250000
...          ...      ...        ...
1455          60     7917     175000
1456          20    13175     210000
1457          70     9042     266500
1458          20     9717     142125
1459          20     9937     147500

[1460 rows x 3 columns]

In [8]:
x_train = train_ds_sub.to_numpy()[:, :2]
y_train = train_ds_sub.to_numpy()[:, 2:]
print(x_train)
print(y_train)

[[   60  8450]
 [   20  9600]
 [   60 11250]
 ...
 [   70  9042]
 [   20  9717]
 [   20  9937]]
[[208500]
 [181500]
 [223500]
 ...
 [266500]
 [142125]
 [147500]]

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(x_train, y_train)
lr

LinearRegression()

In [10]:
# this will show the beta value(s) like, b1, b2 etc
lr.coef_

array([[-90.80079432,   2.04618231]])

In [11]:
# this is the b0 of linear regression equation
lr.intercept_

array([164568.16479065])

In [12]:
train_ds_sub['SalePricePredict'] = lr.predict(x_train)
train_ds_sub

      MSSubClass  LotArea  SalePrice  SalePricePredict
0             60     8450     208500     176410.357609
1             20     9600     181500     182395.499033
2             60    11250     223500     182139.668064
3             70     9550     140000     177753.150202
4             60    14260     250000     188298.676802
...          ...      ...        ...               ...
1455          60     7917     175000     175319.742441
1456          20    13175     210000     189710.600774
1457          70     9042     266500     176713.689591
1458          20     9717     142125     182634.902363
1459          20     9937     147500     183085.062470

[1460 rows x 4 columns]

In [15]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(train_ds_sub['SalePrice'], train_ds_sub['SalePricePredict'])

55146.195339879814

In [29]:
test_ds_sub = test_ds[['MSSubClass', 'LotArea']]
test_ds_sub = test_ds_sub.fillna(test_ds_sub.mean())
x_test = test_ds_sub.to_numpy()
y_predict = lr.predict(x_test)
test_ds_sub['SalePrice'] = y_predict
test_ds_sub['Id'] = test_ds[['Id']]
test_ds_sub[['Id', 'SalePrice']].to_csv('linearReg_Predict.csv', index=False)